BIN_DIR=$TOP_DIR/bin
PACKAGE_DIR=$TOP_DIR/packages
SRC_DIR=$TOP_DIR/src

PACKAGE_HOMEBREW_DIR=$PACKAGE_DIR/homebrew
PACKAGE_APT_DIR=$PACKAGE_DIR/apt
PACKAGE_FISHER_DIR=$PACKAGE_DIR/fisher
SRC_SHELL_DIR=$SRC_DIR/shell
